server:
  port: 7003
spring:
  application:
    name: tg-order-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

