server:
  port: 7003
spring:
  application:
    name: tg-order-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
