server:
  port: 9002
spring:
  application:
    name: tg-user-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tg_user
    username: root
    password: ok
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456



eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
