server:
  port: 9002
spring:
  application:
    name: tg-user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true



#fuzaijunheng
