server:
  port: 9002
spring:
  application:
    name: tg-user-consumer
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true


#支付宝付款
alipay:
  protocol: https
  gatewayHost: openapi.alipaydev.com
  signType: RSA2
  appId: 2021000116698446
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYQK8XGgtr6LUgbY/q+WSfnkoHvoPRypIkSzbrQm25ouaWDwm0AZTiPwyd6zZ+ax+lS+9RzoM4+Lp/5hVNv3H4UOwmb7kT34GBabYj1eyT/QpmsSQSiARBzWvw8g4hgrYXZBs9W/tLHre5ftlyQhximTdVFai/QbGWXOmuSGIpGQHywA4F71A+CvwsFG82vMS3ZbmZylbVM37I58bkdEDb9AXkH7A9E5pGQlSrpIkf2cz6V10gDNA/lD8E+PnK1eySiuNZoTLf1tfhrt6jFwba2kGULXLaCM3MNAb0lb4zHqxRZx8Q+VO5z4/mVSqYCPltTD6dYySksaVYiyf4HkMhAgMBAAECggEAC2Bh9Ob0TYbg6eBl7ZffBfJM89EvhmCNlPqtytx22HUsp6/N+M5ZcqJlbfNiagXVIoPPCRzWP06OmPn3Q4z3lidtzd1xRePgiGv+uSTF/bTdrxizalMRhl00IJflqGlc89h+FJKn71AHSGwLEXeRKWjrcocgydG91E9zApvUAeAHiggIU+sl5VMW9anz5WFB1pcTBmh5NNo3h4B89f9YK/86pCjSI0aye508JIfkNe3/JyDs5fL68k0SlPuTZ4dtkJVL5IOpUtEby0Ca1PPa1cSgqQcyszXKf+kn4OonHbU7QM3zRBqaIk2FbgbZ0EDAAoLrs3bJDqzIF/VtiTnfMQKBgQDrCldKzHtZMWCW9Ma8LA69cJYyNiez7R9jkWNucA4V0jXkupgZ95KtJvLRCwT4uyxGHN5LS0piZHY++GRgwipGM4MyOWoIXmpLXvB1MXqwkDTkbWsZausuQNulHnltw9f/Tit0g1i7GxojFi8+z66Pmw8Occ/XKWz74uXY9poQlQKBgQCl1GjZLuui9qhk3OvcKo+KIjithq/h73rPe3ndruGIYwK8Wh989uNFjv0jcz7CvsrZj4YjMY6uMa/OfNztxO2rs+9btxwluS5Os1cpHTMqw79StsoZvUvZ5qOD3W1/peMkhAhg/y3+JYyBlzQzcuc7zcySlmdqQxQ2nurPoA0JXQKBgQCa9ONeDffYcuRSQahwUL+bB4oOKoP8bH2AQE8EdV3j5wXe+WHj5MPP4li9lv09GvFye//WNhohSkhm9Y3/+KK0S6vYRd/xCoYbkMkJCojvtPMaEkVEqafJg7sLXk8CHdbem+OsWhf6q0CNF0goqfVU+g5wIHq9SLNwUUPlyZcDDQKBgFPpGWzcSyvY9/ihuU9c0ekpy9gykQkYbuJSLqY3+bNTtmyshcZr/zCRXBH2HMnaVTalY1CnoPUP+0/W6sv9m+4ITJPyIfIMtBvqr64EMoHvLv6hs742hQ0roY32G5Q90qQFk1/Rf+pcAa8JXcay28LtLhj2tjmU28OPwm1xJWeZAoGALjMuy1VNHo503d/HI+YUPuRQ80h2woI+jtH3o6dtELha795G1kxrUL1DW3/2ocXSpnnBHka9NAjs3ZTHO8VpQBbO/yn3ztern2lbqY1cXz7JRE5zTKe5GdQ1s7nva2T6ZlxGoJMaS7bHsPrsML+VbORDtEhDfteiiJVkJwFtEsM=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHYWCaGfPc4WXz6F6dsZ8JnGhxTtEWDw9MWRXZ5GM25sLJJYMOgXZ1mOFXrvxTvFNwh95YJfBop/5s2OrglnpYteB/PMpcFUpI4M/lqDNtyqU+W2+G9BSBeFBWdmet29ts6B++b+xgrqpj/U7fzIomCCvcQ4cEd1zwCDJ/Y+gZG/kAk8gir46weRyUij8hSqgWFovQsajkiEoKwae3eC0B1hz0BsP6HvJogY1pdoYnOFXZEDXjNGgZJpwV0Kk9B3XUXT5N4nLqUFFL3WgYAe76jxN+aYPLj5Uqqykw6AKr7ad+6H8/+u3hnLYdlD9qmgR0Bf8UhcSvs8dTgxdo+IlwIDAQAB
  notifyUrl: http://127.0.0.1/alipay.trade.page.pay-JAVA-UTF-8/notify_url.jsp
  returnUrl: http://127.0.0.1/alipay.trade.page.pay-JAVA-UTF-8/return_url.jsp
  encryptKey: vExyHaDQenrZ2ONGLVJgXg==


#fuzaijunheng
