server:
  port: 5001
spring:
  application:
    name: my-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tg_goods
    username: root
    password: ok
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml