server:
  port: 6001
spring:
  application:
    name: tg-leader-provider
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tg_leader
    username: root
    password: ok
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

ribbon:
  ConnectTimeout: 30000